<template>
  <div>
    <v-container fluid id="terms-page-header">
      <v-container>
        <v-row>
          <v-col cols="12">
            <div id="main-title-holder">
              <h1 class="gama-text-h1">Terms</h1>
              <p class="gama-text-subtitle2">Terms and Conditions</p>
            </div>
          </v-col>
        </v-row>
      </v-container>
    </v-container>

    <v-container id="terms-data-container">
      <v-row>
        <v-col cols="12">
          <v-text-field
            he
            class="rounded-ts pr-0"
            dense
            outlined
            hide-details
            v-model="searchQuery"
            label="Search"
          >
            <template slot="append-outer">
              <v-btn dense color="#FFB300" class="white--text">
                <v-icon>mdi-magnify</v-icon>
              </v-btn>
            </template>
          </v-text-field>
        </v-col>
      </v-row>

      <v-row id="list-rows">
        <v-col cols="12" md="3">
          <v-card flat id="terms-navigation" class="mx-auto">
            <v-navigation-drawer absolute width="100%" permanent>
              <v-list>
                <v-list-item
                  active-class="active-title"
                  v-for="(item, index) in termsSection"
                  :to="`#${item.id}`"
                >
                  <v-list-item-title>{{ item.title }}</v-list-item-title>
                </v-list-item>
              </v-list>
            </v-navigation-drawer>
          </v-card>
        </v-col>
        <v-col cols="12" md="9">
          <v-card flat class="mx-auto">
            <v-card-text>
              <div v-for="item in termsSection">
                <div :id="item.id" class="py-8"></div>
                <h2 class="gama-text-h4">
                  {{ item.title }}
                </h2>
                <div v-html="item.describe"></div>
              </div>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<script>
export default {
  auth: false,
  head() {
    return {
      titleTemplate: "%s",
      title: "GamaTrain's Terms and Conditions: Understanding Our Commitment to You",

      meta: [
        {
          hid: "apple-mobile-web-app-title",
          name: "apple-mobile-web-app-title",
          content:
            "GamaTrain's Terms and Conditions: Understanding Our Commitment to You",
        },
        {
          hid: "og:title",
          name: "og:title",
          content:
            "GamaTrain's Terms and Conditions: Understanding Our Commitment to You",
        },
        {
          hid: "og:site_name",
          name: "og:site_name",
          content: "GamaTrain",
        },
        {
          hid: "description",
          name: "description",
          content:
            "Ensure a smooth and secure learning experience by reviewing GamaTrain's Terms and Conditions, outlining our commitment to user privacy and responsible platform usage.",
        },
        {
          hid: "og:description",
          name: "og:description",
          content:
            "Ensure a smooth and secure learning experience by reviewing GamaTrain's Terms and Conditions, outlining our commitment to user privacy and responsible platform usage.",
        },
      ],
    };
  },

  data() {
    return {
      searchQuery: "",
      activeBookmark: null,
      termsSection: [
        {
          id: "introduction",
          title: "Introduction",
          describe:
            "<p class='gama-text-body1'>" +
            "Thank you for choosing the GamaTrain website for your activities. The GamaTrain website" +
            "has" +
            "started its activities with the aim of creating a repository of sample exam questions" +
            "and" +
            "scientific tests for various levels of education. This repository, with questions" +
            "contributed by" +
            "teachers from all over the world, is regularly updated, allowing easy access to sample" +
            "questions" +
            "for students, teachers, and schools across the world through a simple search." +
            "</p>" +
            "<br>" +
            "<p class='gama-text-body1'>" +
            "In order to maintain the rights of the GamaTrain website and ensure the comfort of all" +
            "users," +
            "rules have been established that users are required to follow. If a user violates these" +
            "regulations, the system administrators have the right to remove the content generated by" +
            "that" +
            "user, and in some cases, their dedicated profile, from the system. These rules are fully" +
            "published below and may change at any time. Please pay attention to messages that may" +
            "reach" +
            "users on some days, informing them of the latest website rules. After carefully reading" +
            "these" +
            'rules, check the option "I agree to carefully read the rules and regulations of the' +
            "GamaTrain" +
            'website" and then press the "Register" button.' +
            "</p>" +
            "<br>" +
            "<p class='gama-text-body1'>" +
            'The GamaTrain website may update these "Terms and Conditions" at any time by updating' +
            "the terms" +
            "of use of the website. You are bound and committed to such revisions, so it is necessary" +
            "to" +
            "periodically check this page to be informed of the current conditions and requirements." +
            "With the hope that by implementing the system's rules and future guidelines, we can gain" +
            "the" +
            "satisfaction of our esteemed users." +
            "</p>",
        },
        {
          id: "registration",
          title: "Registration",
          describe:
            "<ul class='gama-text-body1'>" +
            "<li>All users must use appropriate words when registering on the website. In case of" +
            "inappropriate" +
            "or offensive words, the profile of that user will be deleted at the first opportunity." +
            "Please" +
            "use English letters for usernames and passwords.</li>" +
            "<li>Each user is allowed to register one or more unique identifiers and profiles. To" +
            "activate each" +
            "identifier, click on its activation link from your email. For example, a user can" +
            "register both" +
            "as a teacher and as an educational institution on the website.</li>" +
            "<li>" +
            "Respectable users must provide accurate personal information during registration. If" +
            "there is" +
            "any deficiency in the provided information, such as address, phone number, etc. The" +
            "GamaTrain" +
            "website is not responsible." +
            "</li>" +
            "<li>" +
            "Respectable teachers and educational institutions are required to complete their profile" +
            "information accurately and truthfully to enable them to benefit from advertising" +
            "capabilities" +
            "and ensure users' access to accurate information." +
            "</li>" +
            "</ul>",
        },
        {
          id: "content-guidelines",
          title: "Content Guidelines",
          describe:
            "<ul class='gama-text-body1'>" +
            "<li>" +
            "When registering or searching for exams, there is a scientific classification. Teachers" +
            "must" +
            "carefully categorize the exams into different categories to better introduce them to" +
            "other" +
            "users." +
            "</li>" +
            "<li>" +
            "Respectable teachers commit to the authenticity of exam designs. In case of any claims" +
            "by third" +
            "parties regarding the authorship of registered exams, the responsibility lies with the" +
            "registering teacher, and the GamaTrain website management will not be held accountable." +
            "</li>" +
            "<li>" +
            "The GamaTrain website is not responsible for protecting the copyright rights of exam" +
            "creators." +
            "Respectable teachers, by registering exams, grant permission for their publication to" +
            "the" +
            "GamaTrain website. In return, they receive the right to authorship of the exam according" +
            "to the" +
            "assigned shares and values." +
            "</li>" +
            "<li>" +
            "While GamaTrain makes maximum efforts to verify the accuracy and quality of exams using" +
            "an" +
            "expert team, it does not guarantee their accuracy or quality. GamaTrain website bears no" +
            "commitment or responsibility for exams registered by teachers on the site. The exams are" +
            "registered by teachers who have no real or legal relationship with this site. The direct" +
            "responsibility for a registered exam rests with the registering user, and GamaTrain's" +
            "system" +
            "does not claim or guarantee its accuracy or validity." +
            "</li>" +
            "<li>" +
            "The GamaTrain website displays teachers' exams. The exams listed on the system may" +
            "change or be" +
            "updated continuously by teachers. In this regard, the GamaTrain website does not accept" +
            " any " +
            "responsibility for the exams listed on the site, and the GamaTrain system merely" +
            "displays exams" +
            "registered by users." +
            "</li>" +
            "</ul>",
        },
      ],
    };
  },
  mounted() {
    this.observeDiv("introduction");
    this.observeDiv("registration");
    this.observeDiv("content-guidelines");
  },
  methods: {
    observeDiv(targetId) {
      const targetDiv = document.getElementById(targetId);

      const options = {
        root: null, // Use the viewport as the root
        rootMargin: "0px", // Adjusted root margin
        threshold: 0, // Fully in viewport
      };

      const observer = new IntersectionObserver(
        (entries) => this.handleIntersection(entries, targetId),
        options
      );
      observer.observe(targetDiv);
    },
    handleIntersection(entries, targetId) {
      for (const entry of entries) {
        if (entry.isIntersecting) {
          // The target div is fully in the viewport
          this.$router.push({ hash: targetId });

          // Stop observing the target div after alert
          this.stopObserving(targetId);
        }
      }
    },
    stopObserving(targetId) {
      const targetDiv = document.getElementById(targetId);
      if (targetDiv) {
        const observer = this.observers[targetId];
        if (observer) {
          observer.unobserve(targetDiv);
        }
      }
    },
  },
  watch: {},
  computed: {
    filteredItems() {
      if (!this.searchQuery) {
        return this.termsSection;
      }
      const query = this.searchQuery.toLowerCase();
      return this.termsSection.filter((item) => item.title.toLowerCase().includes(query));
    },
  },
};
</script>

<style>
#terms-page-header {
  height: 20rem;
  background: #24292f;
  position: relative;

  #main-title-holder {
    position: absolute;
    margin: auto;
    left: 0;
    right: 0;
    top: 9.7rem;
    text-align: center;

    .gama-text-h1 {
      color: #ffb600;
      margin-bottom: 0.8rem;
    }

    .gama-text-subtitle2 {
      color: #ffb600 !important;
    }
  }
}

#terms-data-container {
  margin-bottom: 1.5rem;

  .v-text-field {
    width: 42.8rem;
    min-height: auto;
    height: 4rem !important;
    border-radius: 3.8rem 0.4rem 0.4rem 3.8rem;

    margin: 1.6rem auto 1.6rem auto;

    .v-input__control > .v-input__slot {
      min-height: auto;
      height: 4rem !important;

      &:before {
        border-style: none;
      }
    }

    .v-input__append-outer {
      margin: 0 0 0 0.8rem !important;

      .v-btn {
        min-width: auto;
        width: 3.9rem !important;
        height: 3.9rem;
        border-radius: 0.4rem 3.8rem 3.8rem 0.4rem;

        .v-icon {
          color: #000;
          font-size: 2.2rem;
        }
      }
    }
  }

  #list-rows {
    .v-card {
      .gama-text-h4 {
        text-align: center;
        margin-bottom: 4.8rem;
      }
    }

    #terms-navigation {
      height: 18.5rem;
      overflow-y: hidden !important;

      .v-navigation-drawer {
        background: rgba(36, 41, 47, 0.05);

        .v-list-item {
          padding: 1.6rem;

          .v-list-item__title {
            color: #24292f;
            font-family: Inter;
            font-size: 2rem;
            font-style: normal;
            font-weight: 500;
            line-height: normal;
          }
        }

        .active-title::before {
          content: "";
          display: block;
          width: 0.4rem;
          height: 100%;
          border-radius: 0.4rem;
          background: #ffb600;
          opacity: 1;
        }
      }
    }
  }
}

@media only screen and (min-width: 600px) {
  #terms-page-header {
    height: 26rem;

    #main-title-holder {
      top: 11.5rem;

      .gama-text-h1 {
        margin-bottom: 0.8rem;
      }
    }
  }

  #terms-data-container {
    margin-bottom: 1.5rem;

    .v-text-field {
      width: 42.8rem;
      min-height: auto;
      height: 4rem !important;
      border-radius: 3.8rem 0.4rem 0.4rem 3.8rem;

      margin: 1.6rem auto 1.6rem auto;

      .v-input__control > .v-input__slot {
        min-height: auto;
        height: 4rem !important;

        &:before {
          border-style: none;
        }
      }

      .v-input__append-outer {
        margin: 0 0 0 0.8rem !important;

        .v-btn {
          min-width: auto;
          width: 3.9rem !important;
          height: 3.9rem;
          border-radius: 0.4rem 3.8rem 3.8rem 0.4rem;

          .v-icon {
            color: #000;
            font-size: 2.2rem;
          }
        }
      }
    }

    #list-rows {
      .v-card {
        .gama-text-h4 {
          text-align: center;
          margin-bottom: 4.8rem;
        }
      }

      #terms-navigation {
        height: 20rem;

        .v-navigation-drawer {
          .v-list-item {
            padding: 1.6rem;

            .v-list-item__title {
              color: #24292f;
              font-family: Inter;
              font-size: 2.4rem;
              font-style: normal;
              font-weight: 500;
              line-height: normal;
            }
          }

          .active-title::before {
            content: "";
            display: block;
            width: 0.4rem;
            height: 100%;
            border-radius: 0.4rem;
            background: #ffb600;
            opacity: 1;
          }

          .v-list-item::after {
            position: absolute;
            bottom: 0;
            content: "";
            display: block;
            width: 80%;
            height: 0.1rem;
            left: 0;
            right: 0;
            margin: auto;
            border-radius: 0.4rem;
            background: #fff;
            opacity: 1;
          }
        }
      }
    }
  }
}

@media only screen and (min-width: 960px) {
  #terms-page-header {
    height: 34rem;
    background: #24292f;
    position: relative;

    #main-title-holder {
      position: absolute;
      margin: auto;
      left: 0;
      right: 0;
      top: 14.6rem;
      text-align: center;

      .gama-text-h1 {
        color: #ffb600;
        margin-bottom: 1.6rem;
      }

      .gama-text-subtitle2 {
        color: #ffb600 !important;
      }
    }
  }

  #terms-data-container {
    margin-bottom: 1.5rem;

    .v-text-field {
      width: 42.8rem;
      min-height: auto;
      height: 4rem !important;
      border-radius: 3.8rem 0.4rem 0.4rem 3.8rem;

      margin: 1.6rem auto 1.6rem auto;

      .v-input__control > .v-input__slot {
        min-height: auto;
        height: 4rem !important;

        &:before {
          border-style: none;
        }
      }

      .v-input__append-outer {
        margin: 0 0 0 0.8rem !important;

        .v-btn {
          min-width: auto;
          width: 3.9rem !important;
          height: 3.9rem;
          border-radius: 0.4rem 3.8rem 3.8rem 0.4rem;

          .v-icon {
            color: #000;
            font-size: 2.2rem;
          }
        }
      }
    }

    #list-rows {
      .v-card {
        .gama-text-h4 {
          text-align: center;
          margin-bottom: 4.8rem;
        }
      }

      #terms-navigation {
        position: sticky;
        top: 10rem;
        height: 64.2rem;

        .v-navigation-drawer {
          /* background: rgba(36, 41, 47, 0.05); */

          .v-list-item {
            padding: 2.4rem;

            .v-list-item__title {
              color: #24292f;
              font-family: Inter;
              font-size: 2.4rem;
              font-style: normal;
              font-weight: 500;
              line-height: normal;
            }
          }

          .active-title::before {
            content: "";
            display: block;
            width: 0.8rem;
            height: 100%;
            border-radius: 0.4rem;
            background: #ffb600;
            opacity: 1;
          }
        }
      }
    }
  }
}
</style>
